### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by frankmeeuwsen** [philnash/bsky-bot#1]
I tried a plain copy from your template with my own .env credentials. I made them as follows (fake handle & app-password of course

BSKY_PASSWORD=here-goes-app-pw
BSKY_HANDLE=myFabHandle

But I get an error when I build and run

XRPCError: Invalid identifier or password
    at ServiceClient.call (/node_modules/@atproto/api/dist/index.js:7099:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BskyAgent.login (/node_modules/@atproto/api/dist/index.js:14759:19)
    at async Bot.run (file:///dist/lib/bot.js:35:9)
    at async file:///dist/index.js:3:14 {
  status: 401,
  error: 'AuthenticationRequired',
  success: false

I changed the handle and password to a string, added them directly in config.ts line 14 and 15 but no luck. I tried the actual password but still no change in error. Might there be a change with the @atproto API? Anything else I can test?

**Comment by olfrygt** [comment]
Hi Frank,
I received the same error but solved it by deleting the **@** from the handle in .env, online _username_.bsky.social
Maybe this helps.

**Comment by josephwb** [comment]
Thanks @olfrygt your solution works perfectly :)
