### ISSUE TITLE
Intermittent XRPCError

### ISSUE THREAD

**Issue by josephwb** [philnash/bsky-bot#6]
I have been using your bot code for a while now, posting every 2 hours for many weeks. Every few hundred posts I get the error below. I thought it might be weird characters, or a message that was too long that was getting rejected, but I print out as much as I can during the GHA run and this doesn't seem to be the case.

I have backtracked through the code to try to find what the problem is, with no success. Was just wondering if you might have an idea I might pursue. 

Regardless, thanks for making this tool available :)
```
/home/runner/work/whalepetunias/whalepetunias/node_modules/@atproto/api/dist/index.js:7099
        throw new XRPCError(resCode, res.body.error, res.body.message);
              ^

XRPCError: UpstreamFailure
    at ServiceClient.call (/home/runner/work/whalepetunias/whalepetunias/node_modules/@atproto/api/dist/index.js:7099:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostRecord.create (/home/runner/work/whalepetunias/whalepetunias/node_modules/@atproto/api/dist/index.js:14503:17)
    at async Bot.run (file:///home/runner/work/whalepetunias/whalepetunias/dist/lib/bot.js:38:13)
    at async file:///home/runner/work/whalepetunias/whalepetunias/dist/index.js:4:14 {
  status: 502,
  error: 'UpstreamFailure',
  success: false
```

**Comment by philnash** [comment]
Hey @josephwb, that appears to be an issue with the Bluesky service. A 502 error is an issue on their side, it's nothing you did.

We could add some error handling that catches this sort of thing and retries. But, aside from that, this error is not the fault of this code.

**Comment by josephwb** [comment]
Cool, thanks @philnash . I figured it was on their end. I appreciate the response.
