### ISSUE TITLE
getPostText Incorrect Output

### ISSUE THREAD

**Issue by tsprout-uk** [philnash/bsky-bot#8]
I'm sure this is a case of me missing something really obvious, but even after changing getPostText.ts as follows, the bot still posts "Hello from the Bluesky API" when it runs.

```
export default async function getPostText() {
  // Generate the text for your post here. You can return a string or a promise that resolves to a string
  return "This is a test";
}
```

Any suggestions on where I might be going wrong?

**Comment by philnash** [comment]
Ah, yes, you will need to build the project again before you run it.

```
npm run build
```

Then 

```
npm start
```

You can also build the project automatically by running:

```
npm run watch
```

That will keep it up to date.

Let me know if that helps.

**Comment by philnash** [comment]
I'm going to close this, but let me know if you're still having issues and we can reopen and sort them out.
